import type { Comercio, Evento, Estacionamento } from '@/types';

/**
 * DADOS REAIS - CENTRO DE ARACAJU/SE
 * Atualizados com localizações exatas fornecidas.
 */

export interface ComercioExtendido extends Comercio {
  localizacao?: string;
  resumo_avaliacoes?: string;
  redes_sociais?: string;
  rating?: number;
  telefone?: string;
  horarioFuncionamento?: string;
}

export const mockComercios: (Comercio & { localizacao: string, resumo_avaliacoes: string, redes_sociais: string, rating: number })[] = [
    {
        "id": "c1",
        "usuarioId": "u1",
        "nome": "Elite Moda | Matriz Rua João Pessoa | Loja de roupas",
        "email": "contato@elitemodaaju.com",
        "telefone": "(79) 3023-5325",
        "localizacao": "R. João Pessoa, 447, Centro, Aracaju - SE",
        "categoria": "Moda Masculina e Feminina",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop",
        "latitude": -10.9125,
        "longitude": -37.0512,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Jeans", "Moda Masculina", "Moda Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.9,
        "resumo_avaliacoes": "Excelente atendimento e preços acessíveis.",
        "redes_sociais": "@elitemodaaju"
    },
    {
        "id": "c2",
        "usuarioId": "u2",
        "nome": "Loja Vesty Aracaju",
        "email": "contato@lojasvesty.com",
        "telefone": "(79) 99820-4137",
        "localizacao": "Rua Geru, 181, Centro, Aracaju - SE",
        "categoria": "Roupas em Geral",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157258/unnamed_migxu3.jpg",
        "latitude": -10.9118,
        "longitude": -37.0525,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Masculina", "Feminina", "Infantil"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.9,
        "resumo_avaliacoes": "Variedade e bom atendimento.",
        "redes_sociais": "@lojasvesty"
    },
    {
        "id": "c3",
        "usuarioId": "u3",
        "nome": "Shopping Box",
        "email": "contato@shoppingboxaju.com",
        "telefone": "(79) 99105-0127",
        "localizacao": "Av. Mamede Paes Mendonça, 41, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157349/unnamed_uhpoqw.jpg",
        "latitude": -10.9085,
        "longitude": -37.0532,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Roupas", "Cosméticos", "Eletrônicos"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.5,
        "resumo_avaliacoes": "Ótimo para compras baratas e atacado.",
        "redes_sociais": "@shopping_boxaju"
    },
    {
        "id": "c4",
        "usuarioId": "u4",
        "nome": "Lojas Torra",
        "email": "contato@lojastorra.com",
        "telefone": "(79) 2104-7888",
        "localizacao": "R. João Pessoa, 74, Centro, Aracaju - SE",
        "categoria": "Roupas e Calçados",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157480/unnamed_uck38v.jpg",
        "latitude": -10.9132,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Varejo", "Moda", "Calçados"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.4,
        "resumo_avaliacoes": "Loja ampla com muitas opções de vestuário.",
        "redes_sociais": "@lojastorra"
    },
    {
        "id": "c5",
        "usuarioId": "u5",
        "nome": "Nótria Plus Size",
        "email": "contato@notriaplussize.com",
        "telefone": "(79) 3024-5007",
        "localizacao": "R. Laranjeiras, 335, Centro, Aracaju - SE",
        "categoria": "Roupas Plus Size",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157522/unnamed_ofe6ma.jpg",
        "latitude": -10.9112,
        "longitude": -37.0518,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Plus Size", "Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.5,
        "resumo_avaliacoes": "Atendimento personalizado e peças modernas.",
        "redes_sociais": "@notriaplussize"
    },
    {
        "id": "c6",
        "usuarioId": "u6",
        "nome": "Atacadão da Alfaiataria",
        "email": "contato@atacadaodaalfaiataria.com",
        "telefone": "(79) 99999-6336",
        "localizacao": "R. São Cristóvão, 431, Centro, Aracaju - SE",
        "categoria": "Roupas (Alfaiataria)",
        "horarioFuncionamento": "08h30 às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157581/unnamed_pnsba8.jpg",
        "latitude": -10.9105,
        "longitude": -37.0522,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Alfaiataria", "Masculina", "Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.9,
        "resumo_avaliacoes": "Qualidade superior e cortes precisos.",
        "redes_sociais": "@atacadaodaalfaiataria"
    },
    {
        "id": "c7",
        "usuarioId": "u7",
        "nome": "Comercial Quase Tudo",
        "email": "contato@quasetudo.com",
        "telefone": "(79) 3224-4805",
        "localizacao": "R. Apulcro Mota, 669, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 13h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157656/unnamed_nygr3z.jpg",
        "latitude": -10.9078,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Papelaria", "Brinquedos", "Utilidades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.6,
        "resumo_avaliacoes": "Encontra-se de tudo um pouco.",
        "redes_sociais": "@quasetudo669"
    },
    {
        "id": "c8",
        "usuarioId": "u8",
        "nome": "Q'Amora | Moda Feminina",
        "email": "contato@qamora.com",
        "telefone": "(79) 99924-5650",
        "localizacao": "R. Itabaianinha, 141, Centro, Aracaju - SE",
        "categoria": "Moda Feminina e Praia",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774157748/unnamed_kpx4mo.jpg",
        "latitude": -10.9115,
        "longitude": -37.0502,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Moda Praia", "Elegante"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.8,
        "resumo_avaliacoes": "Peças lindas e atendimento atencioso.",
        "redes_sociais": "@qamoraoficial"
    },
    {
        "id": "c9",
        "usuarioId": "u9",
        "nome": "Magazine Luiza (João Pessoa)",
        "email": "contato@magazineluiza.com",
        "telefone": "(79) 3198-3000",
        "localizacao": "R. João Pessoa, 320, Centro, Aracaju - SE",
        "categoria": "Eletrodomésticos e Eletrônicos",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774158633/unnamed_nkdcqu.jpg",
        "latitude": -10.9128,
        "longitude": -37.0515,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrônicos", "Móveis", "Varejo"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Bom atendimento e entrega rápida.",
        "redes_sociais": "@magazineluiza"
    },
    {
        "id": "c10",
        "usuarioId": "u10",
        "nome": "Casas Bahia",
        "email": "contato@casasbahia.com",
        "telefone": "(79) 3512-0538",
        "localizacao": "R. São Cristóvão, 231, Centro, Aracaju - SE",
        "categoria": "Móveis e Eletrodomésticos",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774158941/unnamed_cqpnlr.jpg",
        "latitude": -10.9108,
        "longitude": -37.0515,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrodomésticos", "Celulares", "Móveis"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.1,
        "resumo_avaliacoes": "Preços competitivos e boas opções de parcelamento.",
        "redes_sociais": "@casasbahia"
    },
    {
        "id": "c11",
        "usuarioId": "u11",
        "nome": "Marisa",
        "email": "contato@marisa.com",
        "telefone": "(11) 4004-2211",
        "localizacao": "R. João Pessoa, 45, Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159018/unnamed_gqgdcs.jpg",
        "latitude": -10.9135,
        "longitude": -37.0502,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Lingerie", "Varejo"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Boas promoções e variedade de tamanhos.",
        "redes_sociais": "@voudemarisa"
    },
    {
        "id": "c12",
        "usuarioId": "u12",
        "nome": "Riachuelo",
        "email": "contato@riachuelo.com",
        "telefone": "(79) 2106-1500",
        "localizacao": "R. João Pessoa, Centro, Aracaju - SE",
        "categoria": "Moda e Casa",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159111/unnamed_fhrxce.jpg",
        "latitude": -10.913,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Masculina", "Feminina", "Infantil", "Casa"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.4,
        "resumo_avaliacoes": "Loja organizada e com muitas opções.",
        "redes_sociais": "@riachuelo"
    },
    {
        "id": "c13",
        "usuarioId": "u13",
        "nome": "Lojão da China",
        "email": "contato@lojaodachina.com",
        "telefone": "(79) 3211-1064",
        "localizacao": "Av. Carlos Burlamarqui, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h30 às 17h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159184/unnamed_jwt35k.jpg",
        "latitude": -10.9092,
        "longitude": -37.0545,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Utilidades", "Preço Popular"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Muita variedade de produtos úteis.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c14",
        "usuarioId": "u14",
        "nome": "Estação da Moda",
        "email": "contato@estacaodamoda.com",
        "telefone": "(79) 3023-0108",
        "localizacao": "Rua Geru, 217, Centro, Aracaju - SE",
        "categoria": "Moda Feminina e Masculina",
        "horarioFuncionamento": "08h30 às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159403/unnamed_cqbxtt.jpg",
        "latitude": -10.9115,
        "longitude": -37.0528,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Masculina", "Tendências"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.2,
        "resumo_avaliacoes": "Bom custo-benefício.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c15",
        "usuarioId": "u15",
        "nome": "Natura",
        "email": "contato@natura.com",
        "telefone": "(79) 99817-0027",
        "localizacao": "R. Laranjeiras, 154, Centro, Aracaju - SE",
        "categoria": "Cosméticos e Perfumaria",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159463/unnamed_fvn6pn.jpg",
        "latitude": -10.9118,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Perfume", "Beleza", "Cosméticos"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.7,
        "resumo_avaliacoes": "Produtos de qualidade e ótimo atendimento.",
        "redes_sociais": "@naturabroficial"
    },
    {
        "id": "c16",
        "usuarioId": "u16",
        "nome": "Shopping Aracaju",
        "email": "contato@shoppingaracaju.com",
        "telefone": "N/A",
        "localizacao": "R. Apulcro Mota, 630, Centro, Aracaju - SE",
        "categoria": "Shopping Popular",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159596/unnamed_zkvqmr.jpg",
        "latitude": -10.908,
        "longitude": -37.0512,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Centro Comerical"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Local prático para compras rápidas.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c17",
        "usuarioId": "u17",
        "nome": "LOJAADAUI",
        "email": "contato@lojaadaui.com",
        "telefone": "(79) 99948-7854",
        "localizacao": "R. Simão Dias, 213, Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159728/unnamed_q93epl.png",
        "latitude": -10.9122,
        "longitude": -37.0535,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Estilo", "Peças Exclusivas"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.7,
        "resumo_avaliacoes": "Peças exclusivas e bom gosto.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c18",
        "usuarioId": "u18",
        "nome": "Lojão 13",
        "email": "contato@lojao13.com",
        "telefone": "N/A",
        "localizacao": "R. Itabaianinha, 298, Centro, Aracaju - SE",
        "categoria": "Moda Popular",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159776/unnamed_uzlrbl.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Popular", "Acessível"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.0,
        "resumo_avaliacoes": "Preços baixos, ideal para o dia a dia.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c19",
        "usuarioId": "u19",
        "nome": "Shopping Encontro",
        "email": "contato@shoppingencontro.com",
        "telefone": "(79) 99864-5172",
        "localizacao": "Praça João XXIII, 112, Centro, Aracaju - SE",
        "categoria": "Centro Comercial",
        "horarioFuncionamento": "08h30 às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159841/unnamed_uagk8l.jpg",
        "latitude": -10.9088,
        "longitude": -37.0525,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Galeria"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.6,
        "resumo_avaliacoes": "Ambiente agradável e boas lojas.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c20",
        "usuarioId": "u20",
        "nome": "Americanas",
        "email": "contato@americanas.com",
        "telefone": "N/A",
        "localizacao": "R. João Pessoa, Centro, Aracaju - SE",
        "categoria": "Loja de Departamentos",
        "horarioFuncionamento": "08h às 19h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774159959/unnamed_pu6ipv.jpg",
        "latitude": -10.9132,
        "longitude": -37.051,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Departamentos", "Doces", "Eletrônicos"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.4,
        "resumo_avaliacoes": "Variedade de produtos e promoções.",
        "redes_sociais": "@americanas"
    },
    {
        "id": "c21",
        "usuarioId": "u21",
        "nome": "Elite Moda | Filial",
        "email": "contato@elitemodaaju.com",
        "telefone": "(79) 3512-1213",
        "localizacao": "R. Itabaianinha, 293, Centro, Aracaju - SE",
        "categoria": "Moda Masculina e Feminina",
        "horarioFuncionamento": "09h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160006/unnamed_bmnltx.jpg",
        "latitude": -10.9102,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Jeans", "Masculina", "Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Excelente atendimento.",
        "redes_sociais": "@elitemodaaju"
    },
    {
        "id": "c22",
        "usuarioId": "u22",
        "nome": "Malucona Modas",
        "email": "contato@malucona.com",
        "telefone": "N/A",
        "localizacao": "Centro, Aracaju - SE",
        "categoria": "Moda Feminina Popular",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160042/unnamed_heqdlp.jpg",
        "latitude": -10.911,
        "longitude": -37.051,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Popular", "Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.2,
        "resumo_avaliacoes": "Roupas baratas e atuais.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c23",
        "usuarioId": "u23",
        "nome": "Patricinha de Luxo",
        "email": "contato@patricinhadeluxo.com",
        "telefone": "N/A",
        "localizacao": "Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160163/unnamed_trycie.jpg",
        "latitude": -10.9112,
        "longitude": -37.0512,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Jovem", "Festas", "Feminina"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Muitas opções de looks para festas.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c24",
        "usuarioId": "u24",
        "nome": "Rara",
        "email": "contato@rara.com",
        "telefone": "N/A",
        "localizacao": "Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160200/unnamed_z9kq8j.jpg",
        "latitude": -10.9115,
        "longitude": -37.0515,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Casual"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.1,
        "resumo_avaliacoes": "Bom atendimento.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c25",
        "usuarioId": "u25",
        "nome": "Emmanuelle",
        "email": "contato@emmanuelle.com",
        "telefone": "N/A",
        "localizacao": "Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160346/unnamed_qrsxqv.jpg",
        "latitude": -10.9118,
        "longitude": -37.0518,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Modelos Variados"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.0,
        "resumo_avaliacoes": "Variedade de modelos.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c26",
        "usuarioId": "u26",
        "nome": "Lojas Centro",
        "email": "contato@lojascentro.com",
        "telefone": "N/A",
        "localizacao": "R. Capela, 159, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "06h50 às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160432/unnamed_gc1xpd.jpg",
        "latitude": -10.912,
        "longitude": -37.052,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Utilidades", "Variedades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Praticidade no centro.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c27",
        "usuarioId": "u27",
        "nome": "Magazine Luiza (Itabaianinha)",
        "email": "contato@magazineluiza.com",
        "telefone": "(79) 3198-3900",
        "localizacao": "R. Itabaianinha, 283, Centro, Aracaju - SE",
        "categoria": "Eletrodomésticos e Eletrônicos",
        "horarioFuncionamento": "08h às 14h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774162052/unnamed_p5rxwl.jpg",
        "latitude": -10.9105,
        "longitude": -37.0502,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrônicos", "Varejo"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Atendimento padrão da rede.",
        "redes_sociais": "@magazineluiza"
    },
    {
        "id": "c28",
        "usuarioId": "u28",
        "nome": "LOJÃO TOP25",
        "email": "contato@top25.com",
        "telefone": "N/A",
        "localizacao": "R. Itabaianinha, Centro, Aracaju - SE",
        "categoria": "Moda Popular",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160516/unnamed_an8wgm.jpg",
        "latitude": -10.9108,
        "longitude": -37.05,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Popular", "Atacado"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Ótimo para compras em quantidade.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c29",
        "usuarioId": "u29",
        "nome": "LOJAS SÃO JOSÉ",
        "email": "contato@lojasaojose.com",
        "telefone": "(79) 99661-3019",
        "localizacao": "Rua Geru, 165, Centro, Aracaju - SE",
        "categoria": "Centro de Negócios e Comércio",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160607/unnamed_i8tdbt.jpg",
        "latitude": -10.912,
        "longitude": -37.0528,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Serviços"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 3.6,
        "resumo_avaliacoes": "Local centralizado.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c30",
        "usuarioId": "u30",
        "nome": "O Papai",
        "email": "contato@opapai.com",
        "telefone": "N/A",
        "localizacao": "Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160655/unnamed_a7bq83.jpg",
        "latitude": -10.9115,
        "longitude": -37.052,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Tradição", "Variedades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.5,
        "resumo_avaliacoes": "Tradição e bom atendimento.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c31",
        "usuarioId": "u31",
        "nome": "Tudo É",
        "email": "contato@tudoe.com",
        "telefone": "(79) 98143-9237",
        "localizacao": "R. Itabaianinha, 299, Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160713/unnamed_e4heev.jpg",
        "latitude": -10.91,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Moda"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Peças lindas e atuais.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c32",
        "usuarioId": "u32",
        "nome": "Peg Pag Globo",
        "email": "contato@pegpagglobo.com",
        "telefone": "(79) 3214-1647",
        "localizacao": "R. Itabaianinha, 302, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160768/unnamed_oo8wk0.jpg",
        "latitude": -10.9108,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Utilidades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.4,
        "resumo_avaliacoes": "Muita variedade e preços bons.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c33",
        "usuarioId": "u33",
        "nome": "O Rei Imports",
        "email": "contato@oreiimports.com",
        "telefone": "(79) 99818-1901",
        "localizacao": "R. Itabaianinha, 217 - Box 4 e 5, Centro, Aracaju - SE",
        "categoria": "Eletrônicos",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160815/unnamed_cn11zw.jpg",
        "latitude": -10.9112,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrônicos", "Celulares", "Importados"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.8,
        "resumo_avaliacoes": "Melhores preços de importados.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c34",
        "usuarioId": "u34",
        "nome": "Donna Ricca",
        "email": "contato@donnaricca.com",
        "telefone": "N/A",
        "localizacao": "R. Itabaianinha, 217 - Shopping Box Tabajara 22, Centro, Aracaju - SE",
        "categoria": "Calçados",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160860/unnamed_s1pbso.png",
        "latitude": -10.9112,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Calçados", "Feminino"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.6,
        "resumo_avaliacoes": "Calçados confortáveis e bonitos.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c35",
        "usuarioId": "u35",
        "nome": "Josy Joias E Variedades",
        "email": "contato@josyjoias.com",
        "telefone": "(79) 99881-3300",
        "localizacao": "R. Itabaianinha, 217, Centro, Aracaju - SE",
        "categoria": "Joias",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774160903/unnamed_vpwsvv.png",
        "latitude": -10.9112,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Joias", "Acessórios"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Peças de qualidade e bom gosto.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c36",
        "usuarioId": "u36",
        "nome": "ÉQUASE20",
        "email": "contato@equase20.com",
        "telefone": "(79) 99811-6564",
        "localizacao": "R. Itabaianinha, 312, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161186/unnamed_jcrnvs.jpg",
        "latitude": -10.911,
        "longitude": -37.0508,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Preço Único"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Ótimo para achadinhos.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c37",
        "usuarioId": "u37",
        "nome": "Sophia Bella Modas",
        "email": "contato@sophiabella.com",
        "telefone": "(79) 98826-4590",
        "localizacao": "R. Itabaianinha, 282, Centro, Aracaju - SE",
        "categoria": "Moda Evangélica",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161252/unnamed_ou8zz9.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Evangélica"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Peças elegantes e comportadas.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c38",
        "usuarioId": "u38",
        "nome": "Lojão of Cosmetics",
        "email": "contato@lojaoofcosmetics.com",
        "telefone": "(79) 3022-1104",
        "localizacao": "R. José do Prado Franco, 284, Centro, Aracaju - SE",
        "categoria": "Cosméticos",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161355/unnamed_fsylwo.jpg",
        "latitude": -10.9115,
        "longitude": -37.0495,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Cosméticos", "Beleza"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.3,
        "resumo_avaliacoes": "Grande variedade de marcas.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c39",
        "usuarioId": "u39",
        "nome": "Loja Ápice",
        "email": "contato@lojaapice.com",
        "telefone": "N/A",
        "localizacao": "Rua Geru, 151, Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161407/unnamed_p0tmyt.png",
        "latitude": -10.9118,
        "longitude": -37.052,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Moda"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Atendimento excelente.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c40",
        "usuarioId": "u40",
        "nome": "MyllaMel",
        "email": "contato@myllamel.com",
        "telefone": "N/A",
        "localizacao": "R. Itabaianinha, Centro, Aracaju - SE",
        "categoria": "Moda Feminina",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161473/unnamed_qsvyvs.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Feminina", "Moda"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Roupas de qualidade.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c41",
        "usuarioId": "u41",
        "nome": "Thalu Esportes",
        "email": "contato@thaluesprortes.com",
        "telefone": "(79) 3214-5540",
        "localizacao": "R. Santo Amaro, 278 - A, Centro, Aracaju - SE",
        "categoria": "Artigos Esportivos",
        "horarioFuncionamento": "08h30 às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161521/unnamed_b5yydl.jpg",
        "latitude": -10.9115,
        "longitude": -37.0525,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Esportes", "Artigos"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.5,
        "resumo_avaliacoes": "Tudo para o seu esporte.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c42",
        "usuarioId": "u42",
        "nome": "Lev's Cosméticos",
        "email": "contato@levscosmetics.com",
        "telefone": "(79) 98878-3082",
        "localizacao": "R. Itabaianinha, 217, Centro, Aracaju - SE",
        "categoria": "Cosméticos",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161576/unnamed_ckfok1.jpg",
        "latitude": -10.9112,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Cosméticos"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Produtos excelentes.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c43",
        "usuarioId": "u43",
        "nome": "Honyancell",
        "email": "contato@honyancell.com",
        "telefone": "(79) 99651-4183",
        "localizacao": "R. Itabaianinha, 284, Centro, Aracaju - SE",
        "categoria": "Eletrônicos",
        "horarioFuncionamento": "09h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161618/thumbnail_eu3dcr.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrônicos", "Celulares"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Atendimento nota 10.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c44",
        "usuarioId": "u44",
        "nome": "Vip Coiffer Cosméticos",
        "email": "contato@vipcoiffer.com",
        "telefone": "(79) 98134-2919",
        "localizacao": "R. Itabaianinha, Centro, Aracaju - SE",
        "categoria": "Cosméticos",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161683/unnamed_gcmfde.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Cosméticos", "Profissional"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 5.0,
        "resumo_avaliacoes": "Melhores produtos para salão.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c45",
        "usuarioId": "u45",
        "nome": "Impacto Cell",
        "email": "contato@impactocell.com",
        "telefone": "N/A",
        "localizacao": "R. São Cristóvão, 217, Centro, Aracaju - SE",
        "categoria": "Eletrônicos",
        "horarioFuncionamento": "07h30 às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161753/unnamed_isu3gx.jpg",
        "latitude": -10.911,
        "longitude": -37.0515,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Eletrônicos", "Celulares"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.4,
        "resumo_avaliacoes": "Serviço rápido.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c46",
        "usuarioId": "u46",
        "nome": "Shu Yu",
        "email": "contato@shuyu.com",
        "telefone": "N/A",
        "localizacao": "R. Itabaianinha, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161800/unnamed_g5qouj.jpg",
        "latitude": -10.9105,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.0,
        "resumo_avaliacoes": "Muitas opções.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c47",
        "usuarioId": "u47",
        "nome": "D'Tudo",
        "email": "contato@dtudo.com",
        "telefone": "N/A",
        "localizacao": "Av. Mamede Paes Mendonça, 243, Centro, Aracaju - SE",
        "categoria": "Variedades",
        "horarioFuncionamento": "08h às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161897/unnamed_j3ye6j.jpg",
        "latitude": -10.9085,
        "longitude": -37.053,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Utilidades"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.6,
        "resumo_avaliacoes": "Encontra de tudo.",
        "redes_sociais": "N/A"
    },
    {
        "id": "c48",
        "usuarioId": "u48",
        "nome": "Shopping Box Tabajara",
        "email": "contato@shoppingboxtabajara.com",
        "telefone": "(79) 99947-6586",
        "localizacao": "R. Itabaianinha, Centro, Aracaju - SE",
        "categoria": "Centro Comercial",
        "horarioFuncionamento": "08h30 às 18h",
        "imagem": "https://res.cloudinary.com/dtskn1ns3/image/upload/v1774161975/unnamed_mfgrzy.jpg",
        "latitude": -10.9112,
        "longitude": -37.0505,
        "statusAberto": true,
        "favoritada": false,
        "tags": ["Variedades", "Shopping"],
        "produtos": [],
        "avaliacoes": [],
        "rating": 4.5,
        "resumo_avaliacoes": "Ótimo para compras baratas.",
        "redes_sociais": "N/A"
    }
];

export const mockEventos: Evento[] = [
  {
    id: 'e1',
    nome: 'Festival de Cultura do Centro',
    descricao: 'Celebração da música, arte e gastronomia local',
    dataHora: '2026-03-25T10:00:00Z',
    categoria: 'Cultura',
    latitude: -10.9110,
    longitude: -37.0528,
    imagem: 'https://picsum.photos/400/400?random=evento1'
  }
];

export const mockEstacionamentos: Estacionamento[] = [
  {
    id: 'e1',
    nome: 'Estacionamento Centro Aracaju',
    latitude: -10.9115,
    longitude: -37.0515,
    numeroVagas: 50,
    vagasOcupadas: 35,
    status: 'lotado',
    precoHora: 5.00
  },
  {
    id: 'e2',
    nome: 'Parking Rua João Pessoa',
    latitude: -10.9125,
    longitude: -37.0510,
    numeroVagas: 30,
    vagasOcupadas: 28,
    status: 'lotado',
    precoHora: 6.00
  },
  {
    id: 'e3',
    nome: 'Garagem Centro Shopping',
    latitude: -10.9100,
    longitude: -37.0520,
    numeroVagas: 100,
    vagasOcupadas: 45,
    status: 'livre',
    precoHora: 4.50
  }
];

